{{- if not .Values.existingSecret }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubefirst-api.fullname" . }}-bootstrap
  namespace: {{ default kubefirst .Values.prehookJob.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
{{- end }}
---
{{- if not .Values.existingSecret }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubefirst-api.fullname" . }}-bootstrap
  namespace: {{ default kubefirst .Values.prehookJob.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - list
      - get
{{- end }}
---
{{- if not .Values.existingSecret }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubefirst-api.fullname" . }}-bootstrap
  namespace: {{ default kubefirst .Values.prehookJob.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubefirst-api.fullname" . }}-bootstrap
subjects:
  - kind: ServiceAccount
    name: {{ include "kubefirst-api.fullname" . }}-bootstrap
    namespace: {{ default kubefirst .Values.prehookJob.namespace }}
{{- end }}
---
{{- if not .Values.existingSecret }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kubefirst-api.fullname" . }}-bootstrap
  namespace: {{ default kubefirst .Values.prehookJob.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - args:
            - create-k8s-secret
            - --namespace
            - kubefirst
            - --name
            - kubefirst-initial-secrets
          image: public.ecr.aws/kubefirst/kubernetes-toolkit:0.1.3
          imagePullPolicy: IfNotPresent
          name: {{ include "kubefirst-api.fullname" . }}-bootstrap
      restartPolicy: OnFailure
      serviceAccountName: {{ include "kubefirst-api.fullname" . }}-bootstrap
{{- end }}
